- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: aws-honeystash
    group_name: honeystash
    ami_name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180306"

  tasks:
    - include_tasks: roles/honeypots/create_sensor_aws.yml
      when: region is defined and platform == "aws"

    - include_tasks: roles/honeypots/create_sensor_gce.yml
      when: region is defined and platform == "gce"

    - include_tasks: roles/honeypots/setup_cowrie_baremental.yml
      when: sensor is defined