- hosts: cowrie
  become: yes
  become_user: root
  tasks:
    # Install Docker
    - import_tasks: roles/honeypots/setup_docker_centos.yml
      when: ansible_os_family == 'RedHat'
    - import_tasks: roles/honeypots/setup_docker_ubuntu.yml
      when: ansible_os_family == 'Debian'

    # Install cowrie
    - import_tasks: roles/honeypots/setup_cowrie.yml
    