####################################################################
# Install/Setup Filebeat
####################################################################
- name: Install software
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

- name: Install/Setup Filebeat
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - filebeat

- name: Create /etc/filebeat/conf.d
  file:
    path: /etc/filebeat/conf.d
    owner: root
    group: root
    state: directory

- name: Create /etc/filebeat/ssl
  file:
    path: /etc/filebeat/ssl
    owner: root
    group: root
    state: directory

- name: Get SSL cert
  shell: 'openssl s_client -showcerts -connect {{ coh_hostname }}{{ base_domain }}:5044 </dev/null 2> /dev/null|openssl x509 -outform PEM > /etc/filebeat/ssl/logstash.cert'

- name: Copy Filebeat conf
  template:
    src: conf/filebeat/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: 0400

- name: Restart and enable Logstash service
  service:
    name: filebeat
    state: restarted
    enabled: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Filebeat - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None    
