####################################################################
# Install/setup rsysnc
####################################################################
- name: Install software
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - rsync
    - rssh
    
- name: Add rsync user
  user:
    name: '{{ rsync_user }}'
    shell: /usr/bin/rssh
    comment: 'Rsync user for honeypots'

- name: Copy rssh config
  template:
    src: conf/rsync/rssh_client.conf
    dest: /etc/rssh.conf

####################################################################
# Install/setup rsysnc
####################################################################
- name: Create .ssh directory
  file:
    path: /home/{{ rsync_user }}/.ssh
    owner: '{{ rsync_user }}'
    group: '{{ rsync_user }}'
    mode: '0700'
    state: directory
  become: true
  become_user: '{{ rsync_user }}'

- name: Copy ssh keys
  copy: 
    src: conf/ssh/{{ item }}
    dest: $HOME/.ssh/{{ item }}
    owner: '{{ rsync_user }}'
    group: '{{ rsync_user }}'
  with_items:
    - id_rsa
    - id_rsa.pub
  become: true
  become_user: '{{ rsync_user }}'

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Rsync - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None  