####################################################################
# Install/Setup Docker for Ubuntu
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Docker required software
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common
    - python3

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial xerus stable
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Docker
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - docker-ce

- name: Install Docker-py 
  pip:
    name: docker-py
    executable: pip3

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Finished setting up Docker - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None  